services:
    sonata.admin.league:
        class: Mf\ManagerBundle\Admin\Entity\LeagueAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: league, label: "League" }
        arguments:
            - ~
            - Mf\ManagerBundle\Entity\League
            - 'SonataAdminBundle:CRUD' 
        calls:
            - [ setTranslationDomain, [MfManagerBundle] ]

    sonata.admin.tactic:
        class: Mf\ManagerBundle\Admin\Entity\TacticAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: tactic, label: "Tactic" }
        arguments:
            - ~
            - Mf\ManagerBundle\Entity\Tactic
            - 'SonataAdminBundle:CRUD' 
        calls:
            - [ setTranslationDomain, [MfManagerBundle] ]

    sonata.admin.demarcation:
        class: Mf\ManagerBundle\Admin\Entity\DemarcationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: demarcation, label: "Demarcation" }
        arguments:
            - ~
            - Mf\ManagerBundle\Entity\Demarcation
            - 'SonataAdminBundle:CRUD' 
        calls:
            - [ setTranslationDomain, [MfManagerBundle] ]

    sonata.admin.season:
        class: Mf\ManagerBundle\Admin\Entity\SeasonAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: season, label: "Season" }
        arguments:
            - ~
            - Mf\ManagerBundle\Entity\Season
            - 'SonataAdminBundle:CRUD' 
        calls:
            - [ setTranslationDomain, [MfManagerBundle] ]

    sonata.admin.team:
        class: Mf\ManagerBundle\Admin\Entity\TeamAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: team, label: "Team" }
        arguments:
            - ~
            - Mf\ManagerBundle\Entity\Team
            - 'SonataAdminBundle:CRUD' 
        calls:
            - [ setTranslationDomain, [MfManagerBundle] ]