<?php

namespace Mf\ManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HonourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HonourRepository extends EntityRepository
{
}
