<?php

namespace Mf\ManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LeagueSeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeagueSeasonRepository extends EntityRepository
{
}
