<?php

namespace Mf\ManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LeagueSeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeagueSeasonRepository extends EntityRepository
{
    public function getPlayersActive(){
        $query = $this->getEntityManager()->createQuery("
            SELECT p.id, p.name as player_name, p.active, f.name as team_name, d.name as demarcation_name
            FROM MfManagerBundle:LeagueSeason l
            LEFT JOIN l.football_teams f
            LEFT JOIN f.players p
            LEFT JOIN p.demarcations d
            WHERE p.active = 1
            GROUP BY p.name
            ");
        $players = $query->getResult();

        return $players;
    }
}
