<?php

namespace Mf\ManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function getPlayersActive($league_seasson){

        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb
            ->select('Player', 'FootballTeam', 'Demarcation')
            ->from('MfManagerBundle:Player', 'Player')
            ->leftJoin('Player.football_team', 'FootballTeam')
            ->leftJoin('FootballTeam.leagues_seasons', 'LeagueSeason')
            ->leftJoin('Player.demarcations', 'Demarcation')
            ->where('Player.active = 1')
            ->andWhere('LeagueSeason.id = :league_season')
            ->setParameter('league_season', $league_seasson)
        ;

        $query = $qb->getQuery();

        return $query->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }
}
