<?php

namespace Mf\ManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LineupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends EntityRepository
{
}